// <auto-generated />
using Karlson.DataAccess.DbCtx;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Karlson.DataAccess.Migrations
{
    [DbContext(typeof(KarlsonDbCtx))]
    [Migration("20181204095752_AddedName")]
    partial class AddedName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Karlson.Domain.TestEntity", b =>
                {
                    b.Property<int>("TestEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TestId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TestEntityId");

                    b.ToTable("TestEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
